### ISSUE TITLE
Shared runtime 2.2.0-preview1-26614-02 causes Roslyn compilation to fail on xplat sporadically

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#1214]
See: https://ci3.dot.net/job/aspnet_Mvc/job/dev/job/osx-Configuration_Release_prtest/319/console, https://ci3.dot.net/job/aspnet_Mvc/job/dev/job/linux-Configuration_Release_prtest/323/console

The error stack trace:

```
08:59:23    System.IndexOutOfRangeException : Index was outside the bounds of the array.
08:59:23   Stack Trace:
08:59:23      at Microsoft.CodeAnalysis.CodeGen.SwitchIntegralJumpTableEmitter.SwitchBucket.MergeIsAdvantageous(SwitchBucket bucket1, SwitchBucket bucket2) in /_/src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.SwitchBucket.cs:line 282
08:59:23      at Microsoft.CodeAnalysis.CodeGen.SwitchIntegralJumpTableEmitter.GenerateSwitchBuckets(Int32 startLabelIndex, Int32 endLabelIndex) in /_/src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.cs:line 200
08:59:23      at Microsoft.CodeAnalysis.CodeGen.SwitchIntegralJumpTableEmitter.EmitJumpTable() in /_/src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.cs:line 125
08:59:23      at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSwitchHeader(BoundSwitchStatement switchStatement, BoundExpression expression, KeyValuePair`2[] switchCaseLabels, LabelSymbol fallThroughLabel) in /_/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 1174
08:59:23      at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSwitchStatement(BoundSwitchStatement switchStatement) in /_/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 1113
08:59:23      at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) in /_/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 73
```

We've usually seen these sort of errors on account due to errors in cross-gen \ JIT.

**Comment by natemcmaster** [comment]
Can we move this issue to corefx or roslyn?

**Comment by pranavkm** [comment]
Moved to https://github.com/dotnet/coreclr/issues/18525.
