### ISSUE TITLE
macOS 10.14 scouting

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Universe#1227]
Since there is a preview version of macOS Mojave out, we want to make sure our repos can build and tests can run smoothly on it.

**Comment by ajaybhargavb** [comment]
I built and ran Universe tests on a macOS 10.14 machine and the following tests fail consistently.

**ServerTests** - 8 tests
```
ServerComparison.FunctionalTests.HelloWorldTests.HelloWorld(variant: Server: Nginx, TFM: netcoreapp2.2, Type: Standalone, Arch: x64)
ServerComparison.FunctionalTests.HelloWorldTests.HelloWorld(variant: Server: Nginx, TFM: netcoreapp2.2, Type: Portable, Arch: x64)
ServerComparison.FunctionalTests.ResponseCompressionTests.ResponseCompression_NoCompression(variant: Server: Nginx, TFM: netcoreapp2.2, Type: Portable, Arch: x64)
ServerComparison.FunctionalTests.ResponseCompressionTests.ResponseCompression_HostCompression(variant: Server: Nginx, TFM: netcoreapp2.2, Type: Portable, Arch: x64)
ServerComparison.FunctionalTests.ResponseCompressionTests.ResponseCompression_AppAndHostCompression(variant: Server: Nginx, TFM: netcoreapp2.2, Type: Portable, Arch: x64)
ServerComparison.FunctionalTests.ResponseTests.ResponseFormats_Chunked(variant: Server: Nginx, TFM: netcoreapp2.2, Type: Portable, Arch: x64)
ServerComparison.FunctionalTests.ResponseTests.ResponseFormats_ContentLength(variant: Server: Nginx, TFM: netcoreapp2.2, Type: Portable, Arch: x64)
ServerComparison.FunctionalTests.ResponseTests.ResponseFormats_ManuallyChunk(variant: Server: Nginx, TFM: netcoreapp2.2, Type: Portable, Arch: x64)

*Sample failure*
ServerTests           | RUNDOTNET : error Message: 
  ServerTests           |    System.ComponentModel.Win32Exception : No such file or directory
  ServerTests           |   Stack Trace:
  ServerTests           |      at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
  ServerTests           |      at System.Diagnostics.Process.Start()
  ServerTests           |      at System.Diagnostics.ProcessLoggingExtensions.StartAndCaptureOutAndErrToLogger(Process process, String prefix, ILogger logger)
  ServerTests           |      at Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer.Dispose()
  ServerTests           |      at ServerComparison.FunctionalTests.ResponseTests.ResponseFormats(TestVariant variant, Func`3 scenario, String testName) in /Users/dotnet-bot/Github/aspnet/Universe/modules/ServerTests/test/ServerComparison.FunctionalTests/ResponseTests.cs:line 117
  ServerTests           |   --- End of stack trace from previous location where exception was thrown ---
  ServerTests           |   Standard Output Messages:
  ServerTests           |    | [0.001s] TestLifetime Information: Starting test ResponseFormats_ContentLength-Server: Nginx, TFM: netcoreapp2.2, Type: Portable, Arch: x64 at 2018-06-25T19:05:52
  ServerTests           |    | [0.002s] TestLifetime Information: Starting test ResponseFormats_ContentLength_Nginx_netcoreapp2.2_x64_Portable at 2018-06-25T19:05:52
  ServerTests           |    | [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: Executing dotnet /Users/dotnet-bot/Github/aspnet/Universe/modules/ServerTests/test/ServerComparison.TestSites/bin/Debug/netcoreapp2.2/ServerComparison.TestSites.dll --urls http://localhost:53624/ --server Microsoft.AspNetCore.Server.Kestrel
  ServerTests           |    | [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: SET ASPNETCORE_ENVIRONMENT=Responses
  ServerTests           |    | [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
  ServerTests           |    | [0.004s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: SET ASPNETCORE_CONTENTROOT=/Users/dotnet-bot/Github/aspnet/Universe/modules/ServerTests/test/ServerComparison.TestSites
  ServerTests           |    | [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: Started dotnet. Process Id : 66086
  ServerTests           |    | [1.580s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: host process ID 66082 shut down
  ServerTests           |    | [1.580s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Host process shutting down.
  ServerTests           |    | [0.373s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet stdout: Hosting environment: Responses
  ServerTests           |    | [0.373s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet stdout: Content root path: /Users/dotnet-bot/Github/aspnet/Universe/modules/ServerTests/test/ServerComparison.TestSites
  ServerTests           |    | [0.373s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet stdout: Now listening on: http://localhost:53624
  ServerTests           |    | [0.373s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
  ServerTests           |    | [0.375s] TestLifetime Information: Finished test ResponseFormats_ContentLength_Nginx_netcoreapp2.2_x64_Portable in 0.373784s
  ServerTests           |    | [0.379s] TestLifetime Information: Finished test ResponseFormats_ContentLength-Server: Nginx, TFM: netcoreapp2.2, Type: Portable, Arch: x64 in 0.377611s
```

**HttpClientFactory** - 1 test
```
[xUnit.net 00:00:01.3084110]     Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesLiveHandler [FAIL]
  HttpClientFactory     |   Failed   Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesLiveHandler
  HttpClientFactory     | RUNDOTNET : error Message: 
  HttpClientFactory     |    Cleanup entry disposable
  HttpClientFactory     |   Expected: True
  HttpClientFactory     |   Actual:   False
  HttpClientFactory     |   Stack Trace:
  HttpClientFactory     |      at Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesLiveHandler() in /Users/dotnet-bot/Github/aspnet/Universe/modules/HttpClientFactory/test/Microsoft.Extensions.Http.Test/DefaultHttpClientFactoryTest.cs:line 409
  HttpClientFactory     |   --- End of stack trace from previous location where exception was thrown ---
```

**Comment by ajaybhargavb** [comment]
@muratg, could someone with a bit more context on these repos take a look at these failures? I can file issues on the individual repos if necessary.

**Comment by muratg** [comment]
@ajaybhargavb Do you know if these pass on the previous version of the OS? (i.e. regression vs not?)

Are these the only issues, or are you still working on this?  I think we should regroup after the investigation is done.  Perhaps there's a class of errors that you'll uncover...

**Comment by ajaybhargavb** [comment]
> @ajaybhargavb Do you know if these pass on the previous version of the OS? (i.e. regression vs not?)

I didn't run it myself but I checked our CI and these doesn't fail on our exisiting machines.

> Are these the only issues, or are you still working on this?

These were the only failing tests of the entire Universe run. I ran it thrice just to make sure.

**Comment by muratg** [comment]
Will you be able to share the repro machine?

cc @Tratcher could you take a look?  This is the new upcoming Mac OS, we want to make sure it doesn't break us when it's released.

**Comment by ajaybhargavb** [comment]
> Will you be able to share the repro machine?

Yup. It's super easy to remote in to.

**Comment by Tratcher** [comment]
Sounds like NGinx just isn't installed. @BrennanConroy where are our mac agent setup instructions? Is NGinx on the list?

**Comment by ajaybhargavb** [comment]
I ran that script but the tests still fail. Do I need to restart the machine after?

**Comment by BrennanConroy** [comment]
You ran the script?! You only needed the nginx bits from it... restart is always a good idea

**Comment by ajaybhargavb** [comment]
Oops I meant I ran `brew install nginx`. And yes the restart fixed it. The tests pass now

**Comment by muratg** [comment]
Phew!  :relieved:  Thanks folks!

**Comment by ajaybhargavb** [comment]
Probably worth mentioning since I am not sure what causes this. When building Universe and it reaches the step where it builds the metapackages like `Microsoft.AspNetCore.App` there seems to be some funkiness going on with NuGet. By that I mean all the packages from the individual repos that are built are of a different version than what the metapackage tries to acquire. For example,
This is the version (t0068c9e8a) of the package that SignalR built,
```
Successfully created package '/Users/dotnet-bot/Github/aspnet/Universe/modules/SignalR/artifacts/build/Microsoft.AspNetCore.SignalR.Core.1.1.0-preview1-t0068c9e8a.nupkg'
```

But when the metapackage is built it tries to use (t0068ca47d),
```
AppMetapackage will include the following packages
- Package: Microsoft.AspNetCore.SignalR.Core Version: [1.1.0-preview1-t0068ca47d, 1.2.0)
```

This ultimately leads to 
```
error NU1102: Unable to find package Microsoft.AspNetCore.SignalR.Core with version (>= 1.1.0-preview1-t0068ca47d && < 1.2.0)
/Users/dotnet-bot/Github/aspnet/Universe/.w/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 42 version(s) in https://dotnet.myget.org/F/dotnet-core/api/v3/index.json [ Nearest version: 1.0.1 ]
/Users/dotnet-bot/Github/aspnet/Universe/.w/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 40 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json [ Nearest version: 1.0.1 ]
/Users/dotnet-bot/Github/aspnet/Universe/.w/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 8 version(s) in nuget.org [ Nearest version: 1.0.1 ]
/Users/dotnet-bot/Github/aspnet/Universe/.w/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 1 version(s) in /Users/dotnet-bot/Github/aspnet/Universe/artifacts/build/ [ Nearest version: 1.1.0-preview1-t0068c9e8a ]
/Users/dotnet-bot/Github/aspnet/Universe/.w/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in https://dotnet.myget.org/F/aspnetcore-master/api/v3/index.json
/Users/dotnet-bot/Github/aspnet/Universe/.w/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json
/Users/dotnet-bot/Github/aspnet/Universe/.w/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in https://dotnet.myget.org/F/roslyn/api/v3/index.json
/Users/dotnet-bot/Github/aspnet/Universe/.w/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in https://vside.myget.org/F/vsmac/api/v3/index.json
/Users/dotnet-bot/Github/aspnet/Universe/.w/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in https://vside.myget.org/F/vssdk/api/v3/index.json
/Users/dotnet-bot/Github/aspnet/Universe/.w/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj : error NU1102:   - Found 0 version(s) in https://www.myget.org/F/xunit/api/v3/index.json
```

Does anyone know what's going on? @natemcmaster

**Comment by natemcmaster** [comment]
It's a bug in running universe locally. Try running `build.sh` with  `/p:BuildNumber=t000`

**Comment by ajaybhargavb** [comment]
I tried your suggestion and it went past that step but now it's saying the following,
```
Successfully created package '/Users/dotnet-bot/Github/aspnet/Universe/artifacts/build/Microsoft.AspNetCore.Analyzers.0.2.0-alpha1-t000.nupkg'.
  Using NodeJS 8.11.3 from /usr/local/bin/node
  Restoring packages for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.Client.ItemTemplates/Microsoft.DotNet.Web.Client.ItemTemplates.csproj...
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.Client.ItemTemplates/obj/Microsoft.DotNet.Web.Client.ItemTemplates.csproj.nuget.g.props.
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.Client.ItemTemplates/obj/Microsoft.DotNet.Web.Client.ItemTemplates.csproj.nuget.g.targets.
  Restore completed in 149.22 ms for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.Client.ItemTemplates/Microsoft.DotNet.Web.Client.ItemTemplates.csproj.
  Restoring packages for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/DotNetToolsInstaller/DotNetToolsInstaller.csproj...
  Installing dotnet-ef 2.2.0-preview1-t000.
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/DotNetToolsInstaller/obj/DotNetToolsInstaller.csproj.nuget.g.props.
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/DotNetToolsInstaller/obj/DotNetToolsInstaller.csproj.nuget.g.targets.
  Restore completed in 121.88 ms for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/DotNetToolsInstaller/DotNetToolsInstaller.csproj.
  Restoring packages for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/Templates.Test/Templates.Test.csproj...
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/Templates.Test/obj/Templates.Test.csproj.nuget.g.props.
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/Templates.Test/obj/Templates.Test.csproj.nuget.g.targets.
  Restore completed in 488.76 ms for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/Templates.Test/Templates.Test.csproj.
  Restoring packages for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ProjectTemplates/Microsoft.DotNet.Web.ProjectTemplates.csproj...
  Restoring packages for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/Microsoft.DotNet.Web.Spa.ProjectTemplates.csproj...
  Restoring packages for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ItemTemplates/Microsoft.DotNet.Web.ItemTemplates.csproj...
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/obj/Microsoft.DotNet.Web.Spa.ProjectTemplates.csproj.nuget.g.props.
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/obj/Microsoft.DotNet.Web.Spa.ProjectTemplates.csproj.nuget.g.targets.
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ProjectTemplates/obj/Microsoft.DotNet.Web.ProjectTemplates.csproj.nuget.g.props.
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ItemTemplates/obj/Microsoft.DotNet.Web.ItemTemplates.csproj.nuget.g.props.
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ProjectTemplates/obj/Microsoft.DotNet.Web.ProjectTemplates.csproj.nuget.g.targets.
  Generating MSBuild file /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ItemTemplates/obj/Microsoft.DotNet.Web.ItemTemplates.csproj.nuget.g.targets.
  Restore completed in 7.35 ms for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/Microsoft.DotNet.Web.Spa.ProjectTemplates.csproj.
  Restore completed in 10.1 ms for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ProjectTemplates/Microsoft.DotNet.Web.ProjectTemplates.csproj.
  Restore completed in 11.47 ms for /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ItemTemplates/Microsoft.DotNet.Web.ItemTemplates.csproj.
  Microsoft.DotNet.Web.ItemTemplates -> /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ItemTemplates/bin/Debug/netcoreapp2.2/Microsoft.DotNet.Web.ItemTemplates.dll
/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/TemplateTests.targets.in(52): warning : No property value is available for 'BundledAspNetCoreAllTargetFrameworkVersion' [/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/DotNetToolsInstaller/DotNetToolsInstaller.csproj]
/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/TemplateTests.targets.in(52): warning : No property value is available for 'BundledAspNetCoreAllPackageVersion' [/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/DotNetToolsInstaller/DotNetToolsInstaller.csproj]
/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/TemplateTests.targets.in(75): warning : No property value is available for 'BundledAspNetCoreAllTargetFrameworkVersion' [/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/DotNetToolsInstaller/DotNetToolsInstaller.csproj]
/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/TemplateTests.targets.in(75): warning : No property value is available for 'BundledAspNetCoreAllPackageVersion' [/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/DotNetToolsInstaller/DotNetToolsInstaller.csproj]
  Microsoft.DotNet.Web.Client.ItemTemplates -> /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.Client.ItemTemplates/bin/Debug/netcoreapp2.2/Microsoft.DotNet.Web.Client.ItemTemplates.dll
  Microsoft.DotNet.Web.Spa.ProjectTemplates -> /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/bin/Debug/netcoreapp2.2/Microsoft.DotNet.Web.Spa.ProjectTemplates.dll
  DotNetToolsInstaller -> /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/DotNetToolsInstaller/bin/Debug/netcoreapp2.2/DotNetToolsInstaller.dll
/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/TemplateTests.targets.in(52): warning : No property value is available for 'BundledAspNetCoreAllTargetFrameworkVersion' [/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/Templates.Test/Templates.Test.csproj]
/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/TemplateTests.targets.in(52): warning : No property value is available for 'BundledAspNetCoreAllPackageVersion' [/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/Templates.Test/Templates.Test.csproj]
/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/TemplateTests.targets.in(75): warning : No property value is available for 'BundledAspNetCoreAllTargetFrameworkVersion' [/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/Templates.Test/Templates.Test.csproj]
/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/TemplateTests.targets.in(75): warning : No property value is available for 'BundledAspNetCoreAllPackageVersion' [/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/Templates.Test/Templates.Test.csproj]
EmptyWeb-CSharp.csproj.in(20): warning : No property value is available for 'MicrosoftAspNetCoreAppPackageVersion' [/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ProjectTemplates/Microsoft.DotNet.Web.ProjectTemplates.csproj]
WebApi-CSharp.csproj.in(23): warning : No property value is available for 'MicrosoftAspNetCoreAppPackageVersion' [/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ProjectTemplates/Microsoft.DotNet.Web.ProjectTemplates.csproj]
  Microsoft.DotNet.Web.ProjectTemplates -> /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/src/Microsoft.DotNet.Web.ProjectTemplates/bin/Debug/netcoreapp2.2/Microsoft.DotNet.Web.ProjectTemplates.dll
  Templates.Test -> /Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/test/Templates.Test/bin/Debug/netcoreapp2.2/Templates.Test.dll
  Successfully created package '/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/artifacts/build/Microsoft.DotNet.Web.ItemTemplates.2.2.0-preview1-t000.nupkg'.
  Successfully created package '/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/artifacts/build/Microsoft.DotNet.Web.Client.ItemTemplates.2.2.0-preview1-t000.nupkg'.
  Successfully created package '/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/artifacts/build/Microsoft.DotNet.Web.Spa.ProjectTemplates.2.2.0-preview1-t000.nupkg'.
  Successfully created package '/Users/dotnet-bot/Github/aspnet/Universe/modules/Templating/artifacts/build/Microsoft.DotNet.Web.ProjectTemplates.2.2.2.2.0-preview1-t000.nupkg'.
/Users/dotnet-bot/Github/aspnet/Universe/build/repo.targets(257,5): error : Unexpected package artifact with id: dotnet-aspnet-codegenerator [/Users/dotnet-bot/.dotnet/buildtools/korebuild/2.2.0-preview1-17090/KoreBuild.proj]
/Users/dotnet-bot/Github/aspnet/Universe/build/repo.targets(257,5): error : Unexpected package artifact with id: dotnet-aspnet-codegenerator [/Users/dotnet-bot/.dotnet/buildtools/korebuild/2.2.0-preview1-17090/KoreBuild.proj]
/Users/dotnet-bot/Github/aspnet/Universe/build/repo.targets(257,5): error : Unexpected package artifact with id: dotnet-dev-certs [/Users/dotnet-bot/.dotnet/buildtools/korebuild/2.2.0-preview1-17090/KoreBuild.proj]
/Users/dotnet-bot/Github/aspnet/Universe/build/repo.targets(257,5): error : Unexpected package artifact with id: dotnet-dev-certs [/Users/dotnet-bot/.dotnet/buildtools/korebuild/2.2.0-preview1-17090/KoreBuild.proj]
```
and it goes on with the same error for all packages. Is this a known bug too?

**Comment by natemcmaster** [comment]
This can happen if you didn’t clean the artifacts/ folder before running build.sh

**Comment by ajaybhargavb** [comment]
Verified our 1.1 branches also build and run properly on 10.14.
- Verified `dotnet new` applications build and run
- Ran a full build of our repo fro Coherence-Patch
- All tests passed with the exception of a few flaky tests in MvcPrecompilation that we've already address in 2.x (cc @pranavkm).
