### ISSUE TITLE
restore-bower-components target flaky

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Universe#144]
We have started seeing failures in `MusicStore.SPA` project on CI where bower installation fails. For reference I'm copying the bower install logs in success vs failure case. I’m able to see a difference while the bower fails to install. On a working bower installation the command executed is `cmd` with `npm install`. Whereas on failing cases the program executed is `node` throwing this error. 

Working bower install:
```
[09:29:09][restore-bower-components] 'bower' is not recognized as an internal or external command,
[09:29:09][restore-bower-components]    command not found (non-0 exit code)
[09:29:09][restore-bower-components] operable program or batch file.
[09:29:09][restore-bower-components] Testing for command: npm --version
[09:29:10][restore-bower-components] 1.4.14
[09:29:10][restore-bower-components]    command found (0 exit code)
[09:29:10][restore-bower-components] Exec
[09:29:10][restore-bower-components]   program: cmd
[09:29:10][restore-bower-components]   commandline: /C npm install --prefix C:\BuildAgent\work\6feb55fcd711693a\bin\nodejs bower
[09:29:10][restore-bower-components]   workingdir: C:\BuildAgent\work\6feb55fcd711693a
[09:29:30][restore-bower-components] bower@1.3.12 bin\nodejs\node_modules\bower
```

Failing bower install:
```
[13:57:44][restore-bower-components] 'bower' is not recognized as an internal or external command,
[13:57:44][restore-bower-components] operable program or batch file.
[13:57:44][restore-bower-components]    command not found (non-0 exit code)
[13:57:44][restore-bower-components] Testing for command: node --version
[13:57:44][restore-bower-components] v0.10.29
[13:57:44][restore-bower-components]    command found (0 exit code)
[13:57:44][restore-bower-components] Exec
[13:57:44][restore-bower-components]   program: node
[13:57:44][restore-bower-components]   commandline: C:\BuildAgent\work\6feb55fcd711693a\bin\nodejs\node_modules\bower\bin\bower install
[13:57:44][restore-bower-components]   workingdir: C:\BuildAgent\work\6feb55fcd711693a\src\MusicStore.Spa
[13:57:44][restore-bower-components] 
[13:57:44][restore-bower-components] module.js:340
[13:57:44][restore-bower-components]     throw err;
[13:57:44][restore-bower-components]           ^
[13:57:44][restore-bower-components] Error: Cannot find module 'C:\BuildAgent\work\6feb55fcd711693a\bin\nodejs\node_modules\bower\bin\bower'
[13:57:44][restore-bower-components]     at Function.Module._resolveFilename (module.js:338:15)
[13:57:44][restore-bower-components]     at Function.Module._load (module.js:280:25)
[13:57:44][restore-bower-components]     at Function.Module.runMain (module.js:497:10)
[13:57:44][restore-bower-components]     at startup (node.js:119:16)
[13:57:44][restore-bower-components]     at node.js:906:3
[13:57:44][restore-bower-components] Exit code 8 from node
```

**Comment by Praburaj** [comment]
@pranavkm @DamianEdwards

**Comment by dougbu** [comment]
this issue has started showing up in the MVC repo as well.

the underlying problem appears to be the target directory for the bower installation doesn't exist.  example scenario in MVC repo:
1. install node globally (but don't run `npm install --global --quiet bower`)
2. clean repo (`git clean -dfx -e .vs/`)
3. `.\build.cmd --quiet default`
4. see errors in comments above

a small change in _npm.shade to create the target directory avoids this problem.  will send a PR shortly.

**Comment by muratg** [comment]
Doesn't seem to be an issue currently.
