### ISSUE TITLE
Flaky MusicStore test in 1.x patch branches

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Universe#788]
The failing configuration was http://aspnetci/viewLog.html?buildId=389267&tab=buildResultsDiv&buildTypeId=Releases_Windows
```
Warning: Failed to delete directory : Access to the path 'libuv.dll' is denied.
| Information: Trying to drop database 'MusicStore_Test_adb5aa725a294f26ae4ba5e61d9831c6'
| Information: Successfully dropped database MusicStore_Test_adb5aa725a294f26ae4ba5e61d9831c6
| Information: [Time]: Total time taken for this test variation '21.4119484' seconds

[12:08:28] :			 [xunit-test]   
[12:08:28] :			 [xunit-test]   
[12:08:28]F:		 [Test collection for E2ETests.dll (1)] E2ETests.SmokeTests_X64.WindowsOS(serverType: IISExpress, runtimeFlavor: CoreClr, architecture: x64, applicationType: Portable, applicationBaseUrl: "http://localhost:5018/") (2s)
[12:08:31] :			 [xunit-test]   
[12:08:31]F:			 [E2ETests.SmokeTests_X64.WindowsOS(serverType: IISExpress, runtimeFlavor: CoreClr, architecture: x64, applicationType: Portable, applicationBaseUrl: "http://localhost:5018/")] System.OperationCanceledException : Failed to connect, retry limit exceeded.
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.<RetryRequest>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTestHelper.<RunTestsAsync>d__0.MoveNext() in C:\b\w\d6337ac2abf63a4b\.repositories\MusicStore\test\E2ETests\SmokeTestHelper.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTests.<SmokeTestSuite>d__2.MoveNext() in C:\b\w\d6337ac2abf63a4b\.repositories\MusicStore\test\E2ETests\SmokeTests.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTests_X64.<WindowsOS>d__2.MoveNext() in C:\b\w\d6337ac2abf63a4b\.repositories\MusicStore\test\E2ETests\SmokeTests.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by JunTaoLuo** [comment]
Possible issue with cleanup. Passed on rerun so this is a flakiness issue.

**Comment by muratg** [comment]
We don't expect this to be a big blocker so closing this.  

If at any poing this changes, let's reopen.
